model:
  arch: unimernet
  model_type: unimernet
  model_config:
    model_name: /home/sondp/Nhom11_UniMERNet/models/unimernet
    max_seq_len: 512

  tokenizer_name: nougat
  tokenizer_config:
    path: /home/sondp/Nhom11_UniMERNet/models/unimernet

  load_pretrained: false
  load_finetuned: false

datasets:
  formula_rec_train:
    sample_ratio: 1
    vis_processor:
      train:
        name: formula_image_train
        image_size: [192, 672]
    text_processor:
      train:
        name: blip_caption
        max_words: 512
    build_info:
      images: /home/sondp/Nhom11_UniMERNet/data/Images_100k/train/images
      annotation: /home/sondp/Nhom11_UniMERNet/data/Images_100k/train/train.txt

  formula_rec_eval:
    vis_processor:
      eval:
        name: formula_image_eval
        image_size: [192, 672]
    text_processor:
      eval:
        name: blip_caption
        max_words: 512
    build_info:
      images: /home/sondp/Nhom11_UniMERNet/data/Images_100k/val/images
      annotation:  /home/sondp/Nhom11_UniMERNet/data/Images_100k/val/val.txt

run:
  runner: runner_iter
  task: unimernet_train

  lr_sched: linear_warmup_cosine_lr
  init_lr: 5e-5
  min_lr: 1e-6
  warmup_lr: 1e-6
  weight_decay: 0.01

  batch_size_train: 2
  batch_size_eval: 4
  accum_grad_iters: 8
  num_workers: 4

  warmup_steps: 10
  iters_per_inner_epoch: 1000
  max_iters: 125000
  milestone: [1]

  seed: 42
  output_dir: /home/sondp/Nhom11_UniMERNet/outputs/my100k_10k_small
  amp: true
  resume_ckpt_path: null

  evaluate: false
  train_splits: [train]
  valid_splits: [eval]

  device: cuda
  world_size: 1
  dist_url: env://
  distributed: false
  distributed_type: ddp

  generate_cfg:
    temperature: 0.0
